"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const [sidebar, setSidebar] = useState(false);
  return (
    <html lang="en">
        <body className="flex w-full h-screen">
          <Sidebar showSidebar={sidebar} toggleSidebar={()=>setSidebar(!sidebar)} />
          <div className="w-full h-full bg-[#fcfbfe] lg:ml-64 border border-white">
            <Navbar toggleSidebar={()=>setSidebar(!sidebar)} />
            <main className="w-full h-full pt-16 overflow-y-auto">
              {children}
            </main>
          </div>
        </body>
    
    </html>
  );
}
